### ISSUE TITLE
Trouble building the image - vips-dev unsatisfiable constraints on itself

### ISSUE THREAD

**Issue by polarathene** [gazf/alpine-sharp#7]
I've been trying to get a working build of sharp on alpine but keep running into issues, normally it's about `fttw3` but this time with yours it was a bit odd..

```
docker build -t docker-sharp .
Sending build context to Docker daemon   2.56kB
Step 1/7 : FROM node:alpine as builder
alpine: Pulling from library/node
Digest: sha256:49028b628012b5e35479d1f714ae3a6200eab9a8a7b8f3e95159183dbc14910a
Status: Downloaded newer image for node:alpine
 ---> 2ead1ce61ccb
Step 2/7 : RUN set -x &&   apk add     --no-cache --update     --repository https://dl-3.alpinelinux.org/alpine/edge/testing     --repository https://dl-3.alpinelinux.org/alpine/edge/main     vips-dev fftw-dev build-base
 ---> Running in b9efe5c3fa6e
+ apk add --no-cache --update --repository https://dl-3.alpinelinux.org/alpine/edge/testing --repository https://dl-3.alpinelinux.org/alpine/edge/main vips-dev fftw-dev build-base
fetch https://dl-3.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
SSL certificate subject doesn't match host dl-3.alpinelinux.org
WARNING: Ignoring https://dl-3.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz: Permission denied
fetch https://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
SSL certificate subject doesn't match host dl-3.alpinelinux.org
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring https://dl-3.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz: Permission denied
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  vips-dev (missing):
    required by: world[vips-dev]
The command '/bin/sh -c set -x &&   apk add     --no-cache --update     --repository https://dl-3.alpinelinux.org/alpine/edge/testing     --repository https://dl-3.alpinelinux.org/alpine/edge/main     vips-dev fftw-dev build-base' returned a non-zero code: 1
```

vips-dev required by vips-dev...?

**Comment by polarathene** [comment]
Sorry, forgot about this issue. I had reported findings elsewhere in another repo for a docker image I'm interested in using sharp with on alpine.

The above error about the urls is due to `https`, they should work fine with `http` if you want secure `https` url there is an alternative one I think provided by fastly, I could possibly try look that back up for you if you're interested.

Other than that, I also learned that relying on edge repo on non-edge versions of alpine is unreliable, at least with the vips-dev package. Other docker images I had been trying out(Gatsby related) were doing similar for a while but even though nothing had changed since in their Dockerfiles, they were now failing to build like the originally did, something changed on the edge repo package I guess?

The node NPM package for sharp also supports Alpine Linux now with pre-compiled binaries. It will pull those in if using NodeJS v8 or v10 only at present, and only if there is no globally detected libvips/vips-dev package/binary found. So, if you want to take advantage of that, use a specific version of node:alpine as your base(v8 or v10) and avoid building vips-dev from the edge repo. Or use alpine:edge with the edge repo... but I wasn't able to find any maintained node alpine edge Docker images to base off, presumably because edge could be prone to break?

One other related issue I had with the gatsby docker container I built was sometimes `sharp.node` could not be found when searching for the binding, even when it existed at the location it specified.. I added the npm package `bindings.js` which resolved that.

Another issue that I think was related was some dependencies on pngquant, mozjpeg and cwebp(might have been specific to a gatsby sharp plugin package rather than sharp itself). Some of that didn't install well but at the same time didn't error to the point of halting the install process, rather broke during usage(converting a jpeg to webp or the other way around I think). It might have been the sharp plugin used sharp but also paired with `imageoptim`.

**Comment by gazf** [comment]
You finally managed to solve the problem thanks to you.

https://github.com/gazf/alpine-sharp/tree/fix/build-failure

As a solution, I have made "alpine: edge" be used as the base image until Alpine Linux has officially adopted "musl libc".

https://alpinelinux.org/posts/Alpine-Linux-has-switched-to-musl-libc.html
https://github.com/docker/compose/issues/6292
